http_archive(
    name = "gbase",
    url = "https://github.com/imos/gbase/releases/download/v0.8.5/gbase.zip",
    sha256 = "ddf64a35f75ce4206c3538cc55be16494462a6c842fd98ac38eb7e52b4870073",
)

bind(
    name = "base",
    actual = "@gbase//base"
)

bind(
    name = "testing",
    actual = "@gbase//base:testing"
)

bind(
    name = "testing_main",
    actual = "@gbase//base:testing_main"
)

git_repository(
    name = "protobuf",
    tag = "v3.0.0-beta-3.3",
    remote = "https://github.com/google/protobuf.git",
)
