http_archive(
    name = "gbase",
    url = "https://github.com/imos/gbase/releases/download/v0.8.5/gbase.zip",
    sha256 = "0aee114ec1ef15555b2022b8594b70ff3cdf22e3fd42f8e101a98e4c461c9555",
)

bind(
    name = "base",
    actual = "@gbase//base"
)

bind(
    name = "testing",
    actual = "@gbase//base:testing"
)

bind(
    name = "testing_main",
    actual = "@gbase//base:testing_main"
)

git_repository(
    name = "protobuf",
    tag = "v3.0.0-beta-3.3",
    remote = "https://github.com/google/protobuf.git",
)
