licenses(["notice"])

package(default_visibility = ["//visibility:private"])

cc_library(
    name = "gtl",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    visibility = ["//visibility:public"],
    deps = ["//base:base_internal"],
)
