licenses(["notice"])

package(default_visibility = ["//visibility:private"])

cc_library(
    name = "utf",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    visibility = ["//visibility:public"],
)
